apiVersion: v1
kind: Service
metadata:
  name: {{ include "student-service-2.fullname" . }}
  labels:
    {{- include "student-service-2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "student-service-2.selectorLabels" . | nindent 4 }}
